require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.comment"
require "user.fzf-lua"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.indentline"
require "user.alpha"
require "user.autopairs"
require "user.gitsigns"
require "user.treesitter"
require "user.cmp"
require "user.illuminate"
require "user.tree-sitter-twig"
-- require "user.lsp.mason"
-- require "user.dap"
