require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.telescope"
require "user.nvim-web-devicons"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.fortune"
-- require "user.lualine" -- Insert mode display is broken
require "user.indentline"
require "user.alpha"
require "user.autopairs"
require "user.gitsigns"
require "user.treesitter"
require "user.cmp"
require "user.tree-sitter-twig"
require "user.lsp-config" -- mason, lsp-config
require "user.illuminate"
-- require "user.dap"
