notARepository: 'quit'
gui:
  mouseEvents: false
  theme:
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
  nerdfontversions: '2'
  showFileIcons: true
