return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "kaermorchen/tree-sitter-twig",
    },
    opts = {
      -- ensure_installed = "all",
      ensure_installed = {
        "awk",
        "bash",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "dot",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gpg",
        "groovy",
        "html",
        "http",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nginx",
        "php",
        "php_only",
        "robot",
        "robots",
        "ruby",
        "scss",
        "sql",
        "ssh_config",
        "terraform",
        "tmux",
        "toml",
        "twig",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
      ignore_install = { "phpdoc", "wing" },
      highlight = {
        enable = true,
      },
      autopairs = {
        enable = true,
      },
      indent = {
        enable = true,
      },
    },
  },
}
